### ISSUE TITLE
Implementation Suggestion

### ISSUE THREAD

**Issue by htnlabs** [Lukas-Gelbmann/CryptocurrencyTradingBot#2]
Could you make the robot multi-currency? Could the algorithm check multiple assets at the same time? With operations limit in config?

**Comment by Lukas-Gelbmann** [comment]
That would be possible, but it would make the program much more complicated, not only the code but also the configuration. 
The main problem would be that currently only one currency is held when trading, so when BTC / ETH is traded, you always only have either Bitcoin or Ethereum. If you would add BTC / XRP as a second traiding pair and Ethereum is held, an error occurs when there would occur a trading signal for BTC / XRP.

For backtesting an research purposes this feature would be interesting.
